[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install -g pnpm",
  "ELECTRON_SKIP_BINARY_DOWNLOAD=1 PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 pnpm install --ignore-scripts"
]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm run start"
